# Generated by Django 5.2.17 on 2026-09-08 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('CURSANDO', 'Cursando'), ('REGULAR', 'Regular'), ('APROBADO', 'Aprobado'), ('LIBRE', 'Libre')], default='CURSANDO', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='alumnos.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='materias.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia')},
            },
        ),
    ]
